# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='brief',
            field=models.CharField(default='Lorerm Ipsum Dolor', max_length=1000),
            preserve_default=False,
        ),
    ]
