# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_projects_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='subhead',
            field=models.CharField(default='Lorem Ipsum Dolor', max_length=1000),
            preserve_default=False,
        ),
    ]
