# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_projects_subhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='sno',
            field=models.IntegerField(default=0, help_text='Enter 0 for first project'),
        ),
    ]
