# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_projects_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='end_color',
            field=models.CharField(default='#ffffff', help_text='Enter Hex Code, eg #ffffff', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='identifier',
            field=models.CharField(default='Invalid', help_text='Field needs to be unique', max_length=255),
            preserve_default=False,
        ),
    ]
