# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_projects_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='about',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='details',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='idea',
            field=models.CharField(max_length=5000),
        ),
    ]
